services:
    php:
        build: ./docker/php
        volumes:
            - ./app:/var/www/html
            - ./docker/php/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini
        environment:
            PHP_IDE_CONFIG: "serverName=docker-cli"
        links:
            - mariadb
    nginx:
        image: nginx:latest
        ports:
            - '8980:80'
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./app/var/log/nginx:/var/log/nginx
            - ./app:/var/www/html
        links:
            - php
    mariadb:
        image: mariadb:10.6.16
        restart: always
        environment:
            MARIADB_DATABASE: db_name
            MARIADB_USER: db_user
            MARIADB_PASSWORD: db_password
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3411:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/mariadb:/docker-entrypoint-initdb.d

    openapi:
        image: dshanley/vacuum:v0.14.3
        volumes:
            - ./app/apidoc.yaml:/temp/apidoc.yaml
            - ./app/vacuum.yaml:/temp/ruleset.yaml
            - ./app/var/log/vacuum:/work
        profiles:
            - on_demand

volumes:
    mariadb_data:
