controllers:
  resource: ../src/Controller/**/*
  type: attribute
  prefix: /api

api_doc_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: '/api/doc'
    permanent: true
